=== intel/digital-datasheet-creator/edatasheets_creator/jobs/test/output_files/json_to_clang_files/sample_h_file_2-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "inputFile": {
            "type": "string"
        },
        "guid": {
            "type": "string"
        },
        "createdOn": {
            "type": "string"
        },
        "adl-PEcGpioMappingWw394": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "pinName": {
                        "type": "string"
                    },
                    "adl-PRvpNetName": {
                        "type": "string"
                    },
                    "muxConfig": {
                        "type": "string"
                    },
                    "signalDirectionWRTEc": {
                        "type": "string"
                    },
                    "defaultState": {
                        "type": "string"
                    },
                    "pushpullOpenDrain": {
                        "type": "string"
                    },
                    "interruptCapability": {
                        "type": "string"
                    }
                },
                "required": [
                    "pinName"
                ]
            }
        },
        "ecIoExpander": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "ioPins": {
                        "type": "string"
                    },
                    "function": {
                        "type": "string"
                    },
                    "direction": {
                        "type": "string"
                    }
                },
                "required": [
                    "direction",
                    "function",
                    "ioPins"
                ]
            }
        },
        "ecIoExpander2": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "ioPins": {
                        "type": "string"
                    },
                    "function": {
                        "type": "string"
                    },
                    "direction": {
                        "type": "string"
                    }
                },
                "required": [
                    "direction",
                    "function",
                    "ioPins"
                ]
            }
        }
    },
    "required": [
        "adl-PEcGpioMappingWw394",
        "createdOn",
        "description",
        "ecIoExpander",
        "ecIoExpander2",
        "guid",
        "inputFile",
        "title"
    ]
}

=== intel/digital-datasheet-creator/edatasheets_creator/jobs/test/output_files/json_to_clang_files/sample_h_file_2.json
{
    "title": "Datasheet - sample_h_file_2",
    "description": "Describes a part",
    "inputFile": "sample_h_file_2.xlsx",
    "guid": "3a867e5b-28be-4e3f-9c6e-b4127a1c8123",
    "createdOn": "09/13/2022",
    "adl-PEcGpioMappingWw394": [
        {
            "pinName": "GPIO067/VREF2_ADC",
            "adl-PRvpNetName": "GPIO197",
            "muxConfig": "PECI",
            "signalDirectionWRTEc": "Power",
            "defaultState": "Low",
            "pushpullOpenDrain": "Open Drain",
            "interruptCapability": "BOTH"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        },
        {
            "pinName": "GPIO067/VREF2_ADC"
        }
    ],
    "ecIoExpander": [
        {
