=== intel/digital-datasheet-creator/edatasheets_creator/schemas/map-schema.json
{
    "$schema":"http://json-schema.org/draft-04/schema#",
    "title":"Map file schema",
    "description":"This schema provides the structure to validate a map file",
    "type":"object",
    "properties": {
        "description":{
            "type":"string",
            "description": "Description of the map file"
        },
        "guid":{
            "type":"string",
            "description": "A unique identifier of the map file"
        },
        "mapType":{
            "type":"string",
            "description": "A map type of the map file"
        },
        "datasheetDescLocation":{
            "description": "A datasheet description processor that tells the processor where to find the description that is used in the datasheet.",
            "type":"object",
            "properties": {
                "sheetName":{
                    "type":"string",
                    "description": "Name of the sheet where the description is located"
                },
                "row":{
                    "type":"integer",
                    "description": "Row where the description info is located",
                    "minimum": 1
                },
                "col":{
                    "type":"string",
                    "description": "Row where the description info is located",
                    "pattern": "^[A-Z]+$"
                }
            },
            "additionalProperties": false,
            "required":["sheetName", "row", "col"]
        },
        "sheets":{
            "type":"array",
            "description": "A list of sheets to process",
            "items": {
                "type":"object",
                "description": "Description of each sheet to process",
                "properties": {
                    "sheetName":{
                        "type":"string",
                        "description": "The worksheet name to process. Must match in the spreadsheet."
                    },
                    "includeInDatasheet":{
                        "type":"boolean",
                        "description": "Indicates wheter to include in the e-datasheet output file."
                    },
                    "ignoreBlanks":{
                        "type":"boolean",
                        "description": "Ignore blank spaces or not."
                    },
                    "ignoreRows":{
                        "type":"array",
                        "description": "Indicates whether to include blank lines and skip rows. Not implemented yet.",
                        "items": {
                            "type":"integer",
                            "description": "Each row to ignore",
                            "minimum": 1
                        },
                        "uniqueItems": true
                    },
                    "ignoreCols":{
                        "type":"array",
                        "description": "Indicates whether to include blank lines and skip columns.",
                        "items": {
                            "type":"string",
                            "description": "Each column to ignore.",
                            "pattern": "^[A-Z]+$"
                        },
                        "uniqueItems": true
                    },
                    "sections":{
                        "type":"array",
                        "description": "A worksheet can have multiple sections to process. This array enables specific data elements to be included in the e-datasheet.",
                        "items": {
                            "type":"object",
                            "description": "Sections are defined within the scope of a sheet item.",
                            "properties": {
                                "indexOn":{
                                    "type": "object",
                                    "description": "indexOn is an optional construct that creates JSON objects in an e-datasheet that has a unique key.",
                                    "properties": {
                                        "orientation":{
                                            "type": "string",
                                            "description": "Orientation of the datasheet"
                                        },
                                        "header":{
                                            "type": "object",
                                            "description": "Defines where the indexed field is located.",
                                            "properties": {
                                                "row":{
                                                    "type":"integer",
                                                    "description": "Row",
                                                    "minimum": 1
                                                },
                                                "col":{
                                                    "type":"string",
                                                    "description": "Column",
                                                    "pattern": "^[A-Z]+$"
                                                }
                                            },
                                            "additionalProperties": false,
                                            "required":["row", "col"]
                                        },
                                        "dataStartRow":{
                                            "type": "integer",
                                            "description": "Row to start gathering data.",
                                            "minimum": 1
                                        },
                                        "maxRows":{
                                            "type": "integer",
                                            "description": "Max cout of rows to include in the indexing.",
                                            "minimum": 1
                                        }
                                    },
                                    "additionalProperties": false,
                                    "required":["orientation", "header", "dataStartRow", "maxRows"]
                                },
                                "fieldHeaders":{
                                    "type":"object",
                                    "description": "Data fields for the indexed e-datasheet JSON object.",
                                    "properties": {
                                        "row":{
                                            "type":"integer",
                                            "description": "Row for fieldheaders",
                                            "minimum": 1
                                        }
                                    },
                                    "additionalProperties": false,
                                    "required":["row"]
                                },
                                "spans":{
                                    "type":"object",
                                    "description": "Columns where the data is located",
                                    "properties": {
                                        "columns":{
                                            "type":"array",
                                            "description": "Columns to gather the data.",
                                            "items": {
                                                "type":"string",
                                                "description": "Each column to gather information",
                                                "pattern": "^[A-Z]+$"
                                            },
                                            "uniqueItems": true
                                        }
                                    },
                                    "additionalProperties": false,
                                    "required":["columns"]
                                },
                                "groupBy":{
                                    "type":"array",
                                    "description": "Array of grouping objects.",
                                    "items": {
                                        "type":"object",
                                        "description": "Grouping field object",
                                        "properties": {
                                            "name":{
                                                "type":"object",
                                                "description": "Defines in which cell the grouping field information can be found.",
                                                "properties": {
                                                    "row":{
                                                        "type":"integer",
                                                        "description": "Row of the grouping field name",
                                                        "minimum": 1
                                                    },
                                                    "col":{
                                                        "type":"string",
                                                        "description": "Column",
                                                        "pattern": "^[A-Z]+$"
                                                    },
                                                    "valueCol":{
                                                        "type":"string",
                                                        "description": "Optional value column to include.",
                                                        "pattern": "^[A-Z]+$|^\\s*$"
                                                    }
                                                },
                                                "additionalProperties": false,
                                                "required":["row", "col"]
                                            },
                                            "spans":{
                                                "type":"object",
                                                "description": "Defines which columns could be included in the grouping.",
                                                "properties": {
                                                    "columns":{
                                                        "type":"array",
                                                        "description": "Columns to take into account.",
                                                        "items": {
                                                            "type":"string",
                                                            "description": "Columns",
                                                            "pattern": "^[A-Z]+$"
                                                        },
                                                        "uniqueItems": true
                                                    }
                                                },
                                                "additionalProperties": false,
                                                "required":["columns"]
                                            }
                                        },
                                        "additionalProperties": false,
                                        "required":["name", "spans"]
                                    }
                                },
                                "includeTags":{
                                    "type":"array",
                                    "description": "enables you to grab individual areas within a worksheet. It's like a mini-section.",
                                    "items": {
                                        "type":"object",
                                        "description": "Set of row/col to define where the data is.",
                                        "properties": {
                                            "fieldLabel":{
                                                "type":"object",
                                                "description": "Row/col set for a label and a value and you can have as many of these as you want.",
                                                "properties": {
                                                    "row":{
                                                        "type":"integer",
                                                        "description": "Row",
                                                        "minimum": 1
                                                    },
                                                    "col":{
                                                        "type":"string",
                                                        "description": "Column",
                                                        "pattern": "^[A-Z]+$"
                                                    }
                                                },
                                                "additionalProperties": false,
                                                "required":["row", "col"]
                                            },
                                            "fieldValue":{
                                                "type":"object",
                                                "description": "Position where the value is",
                                                "properties": {
                                                    "row":{
                                                        "type":"integer",
                                                        "description": "Row",
                                                        "minimum": 1
                                                    },
                                                    "col":{
                                                        "type":"string",
                                                        "description": "Column",
                                                        "pattern": "^[A-Z]+$"
                                                    }
                                                },
                                                "additionalProperties": false,
                                                "required":["row", "col"]
                                            }
                                        },
                                        "additionalProperties": false,
                                        "required":["fieldLabel", "fieldValue"]
                                    }
                                }
                            },
                            "additionalProperties": false,
                            "required":["fieldHeaders", "spans"]
                        }
                    }
                },
                "additionalProperties": false,
                "required":["sheetName", "includeInDatasheet", "ignoreBlanks", "ignoreRows", "ignoreCols", "sections"]
            },
            "minItems":1,
            "uniqueItems": true
        }
     },
    "additionalProperties": false,
    "required":["description", "guid", "mapType", "sheets"]
 }

=== intel/digital-datasheet-creator/edatasheets_creator/maps/iec-61360-4-det-classifications-map.json
{
    "description": "IEC 61360-4 - IEC/SC 3D - Common Data Dictionary (CDD- V2.0015.0002) - DET Classifications",
    "guid": "d5b5eb4d-b2a2-4a05-92f9-b045fc160bd1",
    "mapType": "spreadsheet",
    "datasheetDescLocation" : {
        "sheetName" : "Export",
        "row" : 12,
        "col" : "A"
    },
    "sheets": [
        {
            "sheetName": "Export",
            "includeInDatasheet" : true,
            "ignoreBlanks" : true,
            "ignoreRows" : [
                
            ],
            "ignoreCols" : [
               
            ],
            "sections" : [ 
                {
                    "indexOn" : {
                        "orientation" : "column",
                        "header" : {
                            "row" : 24,
                            "col" : "B"
                        },
                        "dataStartRow" : 38,
                        "maxRows" : 200
                    },
                    "fieldHeaders" : {
                                "row" : 24                                       
                    },
                    "spans" : {
                        "columns" : [
                            "C",
                            "D",
                            "E",
                            "F",
                            "G"
                        ]
                    }
                }               
            ]
       }        
    ]
}

=== intel/digital-datasheet-creator/edatasheets_creator/maps/AA-007100-DS-4-ANX7498_Datasheet-map.json
{
    "description": "AA-007100-DS-4-ANX7498 Datasheet map file",
    "guid": "d685b823-0888-47f6-a7b5-6d7033bb67e0",
    "mapType": "spreadsheet",
    "datasheetDescLocation" : {
        "sheetName" : "Readme",
        "row" : 1,
        "col" : "A"
    },
    "sheets": [
        {
            "sheetName": "50-pin QFN Descriptions",
            "includeInDatasheet" : true,
            "ignoreBlanks" : true,
            "ignoreRows" : [
                
            ],
            "ignoreCols" : [
               
            ],
            "sections" : [ 
                {
                    "indexOn" : {
                        "orientation" : "column",
                        "header" : {
                            "row" : 1,
                            "col" : "A"
                        },
                        "dataStartRow" : 2,
                        "maxRows" : 100
                    },
                    "fieldHeaders" : {
                                "row" : 1                                       
                    },
                    "spans" : {
                        "columns" : [
                            "B",
                            "C",
                            "D",
                            "E",
                            "F"
                        ]
                    }
                }               
            ]
        }
    ]
}

=== intel/digital-datasheet-creator/edatasheets_creator/maps/LNL_system_thermal_acoustic_specs_map.json
{
	"description": "LNL STAF Map",
	"guid": "a0550d97-e99c-47dc-93b6-a69f18107e34",
	"mapType": "spreadsheet",
	"sheets": [
        {
			"sheetName": "Base System configs MX",
			"includeInDatasheet": true,
			"ignoreBlanks": true,
			"ignoreRows": [],
			"ignoreCols": [],
			"sections": [
				{
					"indexOn": {
							"orientation": "column",
							"header": {
								"row": 1,
								"col": "A"
							},
							"dataStartRow": 2,
							"maxRows": 36
						},
					"fieldHeaders": {
						"row": 1
					},
					"spans": {
						"columns": [
							"A",
							"B",
							"C",
							"D",
							"E"
						]
					}
				}
			]
		},
		{
			"sheetName": "Fanless M Clamshell configs",
			"includeInDatasheet": true,
			"ignoreBlanks": true,
			"ignoreRows": [],
			"ignoreCols": [],
			"sections": [
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 24
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"B"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"B"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 24
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"C",
								"D"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"C",
									"D"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 24
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"E",
								"F"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "E"
							},
							"spans": {
								"columns": [
									"E",
									"F"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 24
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"G",
								"H",
								"I",
								"J"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "G"
							},
							"spans": {
								"columns": [
									"G",
									"H",
									"I",
									"J"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 24
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"K"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "K"
							},
							"spans": {
								"columns": [
									"K"
								]
							}
						}
					]
				}
			]
		},
		{
			"sheetName": "Fanless M tablet configs",
			"includeInDatasheet": true,
			"ignoreBlanks": true,
			"ignoreRows": [],
			"ignoreCols": [],
			"sections": [
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 15
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"B"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"B"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 15
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"C",
								"D"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"C",
									"D"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 15
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"E",
								"F"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "E"
							},
							"spans": {
								"columns": [
									"E",
									"F"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 15
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"G",
								"H",
								"I",
								"J"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "G"
							},
							"spans": {
								"columns": [
									"G",
									"H",
									"I",
									"J"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 15
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"K"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "K"
							},
							"spans": {
								"columns": [
									"K"
								]
							}
						}
					]
				}
			]
		},
		{
			"sheetName": "Fanned M Clamshell configs",
			"includeInDatasheet": true,
			"ignoreBlanks": true,
			"ignoreRows": [],
			"ignoreCols": [],
			"sections": [
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 20
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"B"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"B"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 20
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"C",
								"D"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "B"
							},
							"spans": {
								"columns": [
									"C",
									"D"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 20
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"E",
								"F"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "E"
							},
							"spans": {
								"columns": [
									"E",
									"F"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 20
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"G",
								"H",
								"I",
								"J"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "G"
							},
							"spans": {
								"columns": [
									"G",
									"H",
									"I",
									"J"
								]
							}
						}
					]
				},
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 3,
						"maxRows": 20
					},
					"fieldHeaders": {
							"row": 2
						},
					"spans": {
						"columns": [
								"K"
							]
						},
					"groupBy": [
						{
							"name": {
								"row": 1,
								"col" : "K"
							},
							"spans": {
								"columns": [
									"K"
								]
							}
						}
					]
				}
			]
		},
		{
			"sheetName": "Concurrent workloads",
			"includeInDatasheet": true,
			"ignoreBlanks": true,
			"ignoreRows": [],
			"ignoreCols": [],
			"sections": [
				{
					"indexOn": {
						"orientation": "column",
						"header": {
							"row": 1,
							"col": "A"
						},
						"dataStartRow": 2,
						"maxRows": 7
					},
					"fieldHeaders": {
						"row": 1
					},
					"spans": {
						"columns": [
							"A",
							"B",
							"C"
						]
					}
				}

			]
		}
        
    ]
}
