=== intel/digital-datasheet-creator/edatasheets_creator/jobs/test/output_files/xlsx_to_json_with_map_files/output-schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "inputFile": {
            "type": "string"
        },
        "guid": {
            "type": "string"
        },
        "createdOn": {
            "type": "string"
        },
        "export": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "version": {
                        "type": "integer"
                    },
                    "revision": {
                        "type": "integer"
                    },
                    "versionreleasedate": {
                        "type": "string"
                    },
                    "revisionreleasedate": {
                        "type": "string"
                    },
                    "preferrednameEn": {
                        "type": "string"
                    },
                    "synonymousname": {
                        "type": "string"
                    },
                    "shortnameEn": {
                        "type": "string"
                    },
                    "definitionEn": {
                        "type": "string"
                    },
                    "definitionsource": {
                        "type": "string"
                    },
                    "statuslevel": {
                        "type": "string"
                    },
                    "proposaldate": {
                        "type": "string"
                    },
                    "requestid": {
                        "type": "string"
                    },
                    "noteEn": {
                        "type": "string"
                    },
                    "drawing": {
                        "type": "string"
                    },
                    "codepreferredunit": {
                        "type": "string"
                    },
                    "codesalternativeunits": {
                        "type": "string"
                    }
                },
                "required": [
                    "code",
                    "definitionEn",
                    "definitionsource",
                    "preferrednameEn",
                    "proposaldate",
                    "requestid",
                    "revision",
                    "revisionreleasedate",
                    "shortnameEn",
                    "statuslevel",
                    "version",
                    "versionreleasedate"
                ]
            }
        }
    },
    "required": [
        "createdOn",
        "description",
        "export",
        "guid",
        "inputFile",
        "title"
    ]
}

=== intel/digital-datasheet-creator/edatasheets_creator/jobs/test/output_files/xlsx_to_json_with_map_files/output.json
{
    "title": "Datasheet - export_LISTOFUNITS_sample",
    "description": "#DEFAULT_SUPPLIER:=0112/2///62656_1",
    "inputFile": "export_LISTOFUNITS_sample.xlsx",
    "guid": "1a2aa6e0-0848-4c47-97e8-f625b6f4a282",
    "createdOn": "09/16/2022",
    "export": [
        {
            "code": "9343/4///45678#RST324",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "synonymousname": "Giorgi system",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST325",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST326",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST327",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST328",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST329",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST330",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST331",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST332",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST333",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST334",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST335",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST336",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST337",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST338",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST339",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST340",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
            "shortnameEn": "CGS-emu",
            "definitionEn": "coherent unit system for atomic analyses",
            "definitionsource": "Michael., 1952",
            "statuslevel": "Standard",
            "proposaldate": "2016-05-25",
            "requestid": "T11123"
        },
        {
            "code": "9343/4///45678#RST341",
            "version": 6,
            "revision": 8,
            "versionreleasedate": "2014-02-13",
            "revisionreleasedate": "2014-02-13",
            "preferrednameEn": "CGS‑thermal system of units",
